const dayjs = require("dayjs");

// ============================================================
// MOCK DATA — SKF Marketplace POC
// ============================================================

const shippers = [
  { id: "SHP001", name: "FastFreight Ltd." },
  { id: "SHP002", name: "Logistic Pro" },
  { id: "SHP003", name: "Thai Union" },
  { id: "SHP004", name: "SupplyChain X" },
  { id: "SHP005", name: "Regional Movers" },
];

const carriers = [
  { id: "CAR001", name: "Skyfrog Co., Ltd." },
  { id: "CAR002", name: "CP-Meiji Transport" },
  { id: "CAR003", name: "LogicTech Solutions" },
  { id: "CAR004", name: "Regional Movers" },
  { id: "CAR005", name: "Apex Freight" },
];

const drivers = [
  {
    id: "DRV001",
    code: "DRV-001",
    name: "Sarah J.",
    group: "Fleet Alpha",
    hhid: "810142",
    plate: "1กข-7447",
    vehicle_type: "Refrigerated",
    available_capacity_kg: 470.0,
    pending_jobs: 2,
    rating: 4.8,
    fuel_type: "Diesel",
    fuel_cost_per_km: 3.5,
    fixed_cost: 500,
    time_cost_per_min: 2.0,
    vehicle_specs: {
      weight_kg: 1500,
      volume_cbm: 8.1,
      length_m: 2.5,
      width_m: 1.8,
      height_m: 1.8,
    },
    gps_lat: 13.756,
    gps_lng: 100.501,
  },
  {
    id: "DRV002",
    code: "DRV-038",
    name: "P. Wong",
    group: "Fleet Alpha",
    hhid: "810143",
    plate: "2กข-8812",
    vehicle_type: "Chilled",
    available_capacity_kg: 576.2,
    pending_jobs: 1,
    rating: 4.5,
    fuel_type: "Diesel",
    fuel_cost_per_km: 3.2,
    fixed_cost: 450,
    time_cost_per_min: 1.8,
    vehicle_specs: {
      weight_kg: 1200,
      volume_cbm: 6.5,
      length_m: 2.2,
      width_m: 1.6,
      height_m: 1.6,
    },
    gps_lat: 13.741,
    gps_lng: 100.523,
  },
  {
    id: "DRV003",
    code: "DRV-011",
    name: "K. Robert",
    group: "Guest",
    hhid: "810144",
    plate: "3กค-5544",
    vehicle_type: "Normal",
    available_capacity_kg: 1050.2,
    pending_jobs: 3,
    rating: 4.2,
    fuel_type: "Gasoline",
    fuel_cost_per_km: 2.8,
    fixed_cost: 300,
    time_cost_per_min: 1.5,
    vehicle_specs: {
      weight_kg: 2000,
      volume_cbm: 12.0,
      length_m: 3.0,
      width_m: 2.0,
      height_m: 2.0,
    },
    gps_lat: 13.762,
    gps_lng: 100.489,
  },
];

const customers = [
  { id: "CUST001", name: "Central Retail Distribution" },
  { id: "CUST002", name: "CP-Meiji DC" },
  { id: "CUST003", name: "PTT Chem Plant" },
  { id: "CUST004", name: "Honda Plant" },
  { id: "CUST005", name: "Lotus Hub" },
];

// ---- Jobs (shared state) ----
const now = dayjs();

const jobs = [
  {
    id: "JOB18140",
    shipper_id: "SHP001",
    carrier_id: "CAR001",
    driver_id: null,
    customer_id: "CUST001",
    backend_status: "PENDING_CARRIER",
    job_status: "OPEN",
    vehicle_type_required: "Chilled",
    pickup_due: now.add(0, "day").hour(14).minute(0).second(0).toISOString(),
    delivery_due: now.add(0, "day").hour(18).minute(0).second(0).toISOString(),
    accept_deadline: now
      .add(0, "day")
      .hour(14)
      .minute(12)
      .second(0)
      .toISOString(),
    origin: "BKK-Pathum",
    destination: "Thai Union Hub",
    price: 3500,
    distance_km: 45,
    est_eta_hrs: 1.5,
    total_items: 22,
    total_weight_kg: 450.5,
    total_volume_cbm: 4.32,
    smart_match_pct: 98.0,
    smart_match_drivers: 5,
    remark: "",
    pickup_point: {
      name: "Warehouse Alpha - Main Hub",
      address: "456 Logistics Way, Samut Prakan, TH 10270",
      contact_name: "Somchai K.",
      phone: "087-7447589",
      due_time: "09:30",
      time_window: [
        { from: "09:00", to: "12:00" },
        { from: "13:00", to: "17:00" },
      ],
    },
    delivery_point: {
      name: "Central Retail Distribution",
      address: "122 Sukhumvit Rd, Bangkok, TH 10110",
      contact_name: "Somchai K.",
      phone: "085-4475821",
      due_time: "18:15",
      time_window: [
        { from: "09:00", to: "12:00" },
        { from: "13:00", to: "17:00" },
      ],
    },
    items: [
      {
        code: "SKU-9921",
        description: "Industrial Fan Blades (Type A)",
        type: "Pallet",
        w: 120,
        l: 120,
        h: 150,
        weight: 250.5,
        qty: 1,
        unit: "PACK",
      },
      {
        code: "SKU-4412",
        description: "Hydraulic Fluid (Sealed)",
        type: "Drum",
        w: 60,
        l: 60,
        h: 90,
        weight: 200.0,
        qty: 1,
        unit: "PACK",
      },
    ],
    created_at: now.subtract(1, "hour").toISOString(),
    transfer_history: [
      {
        date_time: now.subtract(1, "hour").toISOString(),
        event: "Sent to Marketplace",
        actor: "John Doe",
        target: null,
        reason: null,
      },
      {
        date_time: now.subtract(55, "minute").toISOString(),
        event: "Published",
        actor: "John Doe",
        target: null,
        reason: null,
      },
    ],
    job_history: [],
  },
  {
    id: "JOB18141",
    shipper_id: "SHP002",
    carrier_id: "CAR003",
    driver_id: null,
    customer_id: "CUST002",
    backend_status: "PENDING_DRIVER",
    job_status: "OPEN",
    vehicle_type_required: "Chilled",
    pickup_due: now.add(0, "day").hour(16).minute(30).second(0).toISOString(),
    delivery_due: now.add(1, "day").hour(9).minute(0).second(0).toISOString(),
    accept_deadline: now
      .add(0, "day")
      .hour(16)
      .minute(58)
      .second(0)
      .toISOString(),
    origin: "DC-Nongkhai",
    destination: "CP-Meiji DC",
    price: 5200,
    distance_km: 62,
    est_eta_hrs: 2.0,
    total_items: 15,
    total_weight_kg: 320.0,
    total_volume_cbm: 3.1,
    smart_match_pct: 85.0,
    smart_match_drivers: 3,
    remark: "",
    pickup_point: {
      name: "DC Nongkhai Central",
      address: "89 Nongkhai Industrial Rd, Nongkhai, TH 43000",
      contact_name: "Wichai P.",
      phone: "083-1234567",
      due_time: "16:30",
      time_window: [{ from: "14:00", to: "18:00" }],
    },
    delivery_point: {
      name: "CP-Meiji DC",
      address: "321 CP Way, Bangkok, TH 10900",
      contact_name: "Admin CP",
      phone: "02-999-1234",
      due_time: "09:00",
      time_window: [{ from: "08:00", to: "12:00" }],
    },
    items: [
      {
        code: "SKU-2201",
        description: "Dairy Mix Box",
        type: "Box",
        w: 40,
        l: 40,
        h: 40,
        weight: 20.0,
        qty: 15,
        unit: "BOX",
      },
    ],
    created_at: now.subtract(2, "hour").toISOString(),
    transfer_history: [],
    job_history: [
      {
        date_time: now.subtract(2, "hour").toISOString(),
        event: "Approved",
        actor: "[Admin] Alex Park",
        target: null,
        reason: null,
      },
      {
        date_time: now.subtract(90, "minute").toISOString(),
        event: "Driver Assigned",
        actor: "[Admin] Siriwat P.",
        target: null,
        reason: null,
      },
    ],
  },
  {
    id: "JOB18142",
    shipper_id: "SHP003",
    carrier_id: "CAR001",
    driver_id: "DRV001",
    customer_id: "CUST003",
    backend_status: "CONFIRMED",
    job_status: "RECEIVED",
    vehicle_type_required: "Frozen",
    pickup_due: now.add(1, "day").hour(8).minute(0).second(0).toISOString(),
    delivery_due: now.add(1, "day").hour(14).minute(0).second(0).toISOString(),
    accept_deadline: null,
    origin: "BKK-Rayong",
    destination: "PTT Chem Plant",
    price: 4800,
    distance_km: 180,
    est_eta_hrs: 3.5,
    total_items: 10,
    total_weight_kg: 800.0,
    total_volume_cbm: 7.2,
    smart_match_pct: 92.0,
    smart_match_drivers: 4,
    remark: "Handle with care",
    pickup_point: {
      name: "BKK Rayong Hub",
      address: "55 Rayong Industrial, Rayong, TH 21000",
      contact_name: "Anan S.",
      phone: "038-001234",
      due_time: "08:00",
      time_window: [{ from: "07:00", to: "10:00" }],
    },
    delivery_point: {
      name: "PTT Chem Plant Gate 3",
      address: "PTT Industrial Estate, Rayong, TH 21150",
      contact_name: "PTT Security",
      phone: "038-999999",
      due_time: "14:00",
      time_window: [{ from: "12:00", to: "16:00" }],
    },
    items: [
      {
        code: "SKU-5501",
        description: "Chemical Reagent A",
        type: "Drum",
        w: 60,
        l: 60,
        h: 90,
        weight: 80.0,
        qty: 10,
        unit: "DRUM",
      },
    ],
    created_at: now.subtract(5, "hour").toISOString(),
    transfer_history: [],
    job_history: [
      {
        date_time: now.subtract(5, "hour").toISOString(),
        event: "Approved",
        actor: "[Admin] Alex Park",
        target: null,
        reason: null,
      },
      {
        date_time: now.subtract(4, "hour").toISOString(),
        event: "Driver Assigned",
        actor: "[Admin] Siriwat P.",
        target: null,
        reason: null,
      },
      {
        date_time: now.subtract(3, "hour").toISOString(),
        event: "Driver Accepted",
        actor: "[Driver] Sarah J.",
        target: null,
        reason: null,
      },
    ],
  },
  {
    id: "JOB18143",
    shipper_id: "SHP004",
    carrier_id: "CAR002",
    driver_id: "DRV002",
    customer_id: "CUST004",
    backend_status: "COMPLETED",
    job_status: "COMPLETED",
    vehicle_type_required: "Normal",
    pickup_due: now
      .subtract(1, "day")
      .hour(10)
      .minute(15)
      .second(0)
      .toISOString(),
    delivery_due: now
      .subtract(1, "day")
      .hour(15)
      .minute(0)
      .second(0)
      .toISOString(),
    accept_deadline: null,
    origin: "DC-Ayutthaya",
    destination: "Honda Plant",
    price: 2900,
    distance_km: 75,
    est_eta_hrs: 1.8,
    total_items: 30,
    total_weight_kg: 600.0,
    total_volume_cbm: 5.5,
    smart_match_pct: 60.0,
    smart_match_drivers: 2,
    remark: "",
    pickup_point: {
      name: "Ayutthaya DC",
      address: "100 Ayutthaya Industrial, Ayutthaya, TH 13000",
      contact_name: "Noi K.",
      phone: "035-111222",
      due_time: "10:15",
      time_window: [{ from: "09:00", to: "11:00" }],
    },
    delivery_point: {
      name: "Honda Plant Main Gate",
      address: "Honda Manufacturing, Ayutthaya, TH 13120",
      contact_name: "Honda Logistics",
      phone: "035-444555",
      due_time: "15:00",
      time_window: [{ from: "13:00", to: "17:00" }],
    },
    items: [
      {
        code: "SKU-7701",
        description: "Auto Parts Box Set",
        type: "Box",
        w: 50,
        l: 50,
        h: 50,
        weight: 20.0,
        qty: 30,
        unit: "BOX",
      },
    ],
    created_at: now.subtract(2, "day").toISOString(),
    transfer_history: [],
    job_history: [],
  },
  {
    id: "JOB18144",
    shipper_id: "SHP005",
    carrier_id: null,
    driver_id: null,
    customer_id: "CUST005",
    backend_status: "REJECTED_ADMIN",
    job_status: "OPEN",
    vehicle_type_required: "Normal",
    pickup_due: now.add(1, "day").hour(14).minute(0).second(0).toISOString(),
    delivery_due: now.add(1, "day").hour(19).minute(0).second(0).toISOString(),
    accept_deadline: null,
    origin: "BKK-Rayong",
    destination: "Lotus Hub",
    price: 3100,
    distance_km: 30,
    est_eta_hrs: 1.0,
    total_items: 5,
    total_weight_kg: 150.0,
    total_volume_cbm: 1.2,
    smart_match_pct: 45.0,
    smart_match_drivers: 1,
    remark: "",
    pickup_point: {
      name: "Rayong Warehouse B",
      address: "77 East Industrial, Rayong, TH 21000",
      contact_name: "Chai P.",
      phone: "038-777888",
      due_time: "14:00",
      time_window: [{ from: "12:00", to: "16:00" }],
    },
    delivery_point: {
      name: "Lotus Hub Central",
      address: "Lotus Distribution Center, Bangkok, TH 10700",
      contact_name: "Lotus Log",
      phone: "02-888-7777",
      due_time: "19:00",
      time_window: [{ from: "17:00", to: "20:00" }],
    },
    items: [
      {
        code: "SKU-3301",
        description: "Fresh Produce Crate",
        type: "Crate",
        w: 60,
        l: 40,
        h: 30,
        weight: 30.0,
        qty: 5,
        unit: "CRATE",
      },
    ],
    created_at: now.subtract(6, "hour").toISOString(),
    transfer_history: [],
    job_history: [
      {
        date_time: now.subtract(3, "hour").toISOString(),
        event: "Admin Rejected",
        actor: "[Admin] Rungchat D.",
        target: null,
        reason: "No available drivers",
      },
    ],
  },
  // DRAFT job for Outbound
  {
    id: "JOB18137",
    shipper_id: "CAR001",
    carrier_id: null,
    driver_id: null,
    customer_id: "CUST003",
    backend_status: "DRAFT",
    job_status: "INCOMPLETE",
    vehicle_type_required: null,
    pickup_due: now.add(2, "day").hour(8).minute(0).second(0).toISOString(),
    delivery_due: now.add(2, "day").hour(16).minute(0).second(0).toISOString(),
    accept_deadline: null,
    origin: "BKK-Rayong",
    destination: "PTT Chem",
    price: null,
    distance_km: null,
    est_eta_hrs: null,
    total_items: 5,
    total_weight_kg: 200.0,
    total_volume_cbm: 2.0,
    smart_match_pct: null,
    smart_match_drivers: null,
    remark: "",
    pickup_point: {
      name: "BKK Rayong Hub",
      address: "55 Rayong Industrial, Rayong, TH 21000",
      contact_name: null,
      phone: null,
      due_time: null,
      time_window: [],
    },
    delivery_point: {
      name: "PTT Chem Plant",
      address: "PTT Industrial Estate, Rayong, TH 21150",
      contact_name: null,
      phone: null,
      due_time: null,
      time_window: [],
    },
    items: [
      {
        code: "SKU-0011",
        description: "Sample Item",
        type: "Box",
        w: 0,
        l: 0,
        h: 0,
        weight: 0,
        qty: 5,
        unit: "BOX",
      },
    ],
    created_at: now.subtract(30, "minute").toISOString(),
    transfer_history: [
      {
        date_time: now.subtract(30, "minute").toISOString(),
        event: "Sent to Marketplace",
        actor: "John Doe",
        target: null,
        reason: null,
      },
    ],
    job_history: [],
  },
  {
    id: "JOB18145",
    shipper_id: "SHP001",
    carrier_id: "CAR001",
    driver_id: null,
    customer_id: "CUST002",
    backend_status: "PENDING_DRIVER",
    job_status: "OPEN",
    vehicle_type_required: "Normal",
    pickup_due: now.add(0, "day").hour(17).minute(0).second(0).toISOString(),
    delivery_due: now.add(1, "day").hour(10).minute(0).second(0).toISOString(),
    accept_deadline: now
      .add(0, "day")
      .hour(17)
      .minute(45)
      .second(0)
      .toISOString(),
    origin: "BKK-Samutprakarn",
    destination: "CP-Meiji DC",
    price: 2800,
    distance_km: 35,
    est_eta_hrs: 1.2,
    total_items: 8,
    total_weight_kg: 240.0,
    total_volume_cbm: 2.16,
    smart_match_pct: 88.0,
    smart_match_drivers: 3,
    remark: "",
    pickup_point: {
      name: "Samutprakarn Warehouse",
      address: "200 Industrial Ring Rd, Samut Prakan, TH 10280",
      contact_name: "Kamon T.",
      phone: "02-333-4455",
      due_time: "17:00",
      time_window: [{ from: "15:00", to: "19:00" }],
    },
    delivery_point: {
      name: "CP-Meiji DC",
      address: "321 CP Way, Bangkok, TH 10900",
      contact_name: "Admin CP",
      phone: "02-999-1234",
      due_time: "10:00",
      time_window: [{ from: "08:00", to: "12:00" }],
    },
    items: [
      {
        code: "SKU-8801",
        description: "Frozen Yogurt Packs",
        type: "Box",
        w: 30,
        l: 30,
        h: 20,
        weight: 30.0,
        qty: 8,
        unit: "BOX",
      },
    ],
    created_at: now.subtract(3, "hour").toISOString(),
    transfer_history: [],
    job_history: [
      {
        date_time: now.subtract(3, "hour").toISOString(),
        event: "Approved",
        actor: "[Admin] Pitchayada K.",
        target: null,
        reason: null,
      },
    ],
  },
  {
    id: "JOB18146",
    shipper_id: "SHP002",
    carrier_id: "CAR001",
    driver_id: "DRV003",
    customer_id: "CUST004",
    backend_status: "DRIVER_ASSIGNED",
    job_status: "OPEN",
    vehicle_type_required: "Normal",
    pickup_due: now.add(0, "day").hour(18).minute(30).second(0).toISOString(),
    delivery_due: now.add(1, "day").hour(9).minute(0).second(0).toISOString(),
    accept_deadline: now
      .add(0, "day")
      .hour(18)
      .minute(50)
      .second(0)
      .toISOString(),
    origin: "DC-Bangna",
    destination: "Honda Plant",
    price: 3200,
    distance_km: 55,
    est_eta_hrs: 1.5,
    total_items: 12,
    total_weight_kg: 380.0,
    total_volume_cbm: 3.24,
    smart_match_pct: 76.0,
    smart_match_drivers: 2,
    remark: "Fragile items",
    pickup_point: {
      name: "Bangna DC",
      address: "999 Bangna-Trad Rd, Bangkok, TH 10260",
      contact_name: "Prasert W.",
      phone: "02-555-6677",
      due_time: "18:30",
      time_window: [{ from: "17:00", to: "20:00" }],
    },
    delivery_point: {
      name: "Honda Plant Main Gate",
      address: "Honda Manufacturing, Ayutthaya, TH 13120",
      contact_name: "Honda Logistics",
      phone: "035-444555",
      due_time: "09:00",
      time_window: [{ from: "08:00", to: "11:00" }],
    },
    items: [
      {
        code: "SKU-9901",
        description: "Honda Engine Parts",
        type: "Crate",
        w: 80,
        l: 60,
        h: 45,
        weight: 31.67,
        qty: 12,
        unit: "CRATE",
      },
    ],
    created_at: now.subtract(4, "hour").toISOString(),
    transfer_history: [],
    job_history: [
      {
        date_time: now.subtract(4, "hour").toISOString(),
        event: "Approved",
        actor: "[Admin] Pitchayada K.",
        target: null,
        reason: null,
      },
      {
        date_time: now.subtract(3, "hour").toISOString(),
        event: "Driver Assigned",
        actor: "[Admin] Pitchayada K.",
        target: null,
        reason: null,
      },
    ],
  },
];

module.exports = { jobs, drivers, carriers, shippers, customers };
